# flake8: noqa: E402

import os
import sys

from prompttrail.agent.hooks._core import ResetDataHook
from prompttrail.agent.templates.anthropic import AnthropicToolingTemplate

sys.path.append(os.path.abspath("."))


from examples.dogfooding.dogfooding_tools import (
    CreateOrOverwriteFile,
    EditFile,
    ExecuteCommand,
    ReadFile,
    ReadImportantFiles,
    TreeDirectory,
)
from prompttrail.agent.runners import CommandLineRunner
from prompttrail.agent.templates import LinearTemplate, LoopTemplate, UserTemplate
from prompttrail.agent.user_interaction import UserInteractionTextCLIProvider
from prompttrail.core import Session
from prompttrail.models.anthropic import AnthropicConfig, AnthropicModel, AnthropicParam

# logging.basicConfig(level=logging.DEBUG)
# disable_noisy_loggers()

tools_to_use = [
    ReadImportantFiles(),
    ExecuteCommand(),
    ReadFile(),
    TreeDirectory(),
    CreateOrOverwriteFile(),
    EditFile(),
]

templates = LinearTemplate(
    templates=[
        UserTemplate(
            content="""
Please help me improve my LLM library, PromptTrail. With the tools you provided, you can execute any linux command.

Note:
# Important Rules for Commits
- Always prefix commit message titles with '[coding-agent]'
- Add a note at the end of commit message: "Note: This commit was automatically generated by coding_agent.py using Claude"

# Project Rules:
{{clinerules}}
""",
            after_transform=ResetDataHook(),
        ),
        LoopTemplate(
            [
                UserTemplate(
                    description="Input:",
                ),
                AnthropicToolingTemplate(tools=tools_to_use),
            ]
        ),
    ],
)

configuration = AnthropicConfig(api_key=os.environ["ANTHROPIC_API_KEY"])
parameter = AnthropicParam(
    model_name="claude-3-5-sonnet-latest",
    temperature=1,
    max_tokens=4096,
    tools=tools_to_use,
)
model = AnthropicModel(configuration=configuration)

runner = CommandLineRunner(
    model=model,
    parameters=parameter,
    template=templates,
    user_interaction_provider=UserInteractionTextCLIProvider(),
)

initial_session = Session(
    initial_metadata={
        # read .clinerules file
        "clinerules": open(".clinerules").read(),
    }
)
runner.run(session=initial_session)
