name: Automated Code Review Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    name: AI-Powered Code Analysis
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        # Required for TreeDirectory Tool functionality
        run: |
          sudo apt update && sudo apt install -y tree
      - name: Configure Virtual Environment Cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements-dev.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Initialize Python Environment
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-dev.lock      
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV      
      - name: Execute Automated Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          BOT_NAME: ${{ github.workflow }}
        run: |
          . .venv/bin/activate
          python examples/dogfooding/auto_code_review.py
