name: Quality Assurance Pipeline

on:
  - pull_request

jobs:
  test:
    name: Code Quality & Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Note: Future expansion planned for additional Python versions
        python-version: ["3.11"]
    steps:
        - uses: actions/checkout@v4
        - name: Initialize Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install System Dependencies
          # Required for TreeDirectory Tool functionality
          run: |
            sudo apt update && sudo apt install -y tree
        - name: Configure Virtual Environment Cache
          uses: actions/cache@v4
          with:
            path: .venv
            key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements-dev.lock') }}
            restore-keys: |
              ${{ runner.os }}-venv-
        - name: Initialize Python Environment
          run: |
            python -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements-dev.lock      
        - name: Configure PYTHONPATH
          run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV      
        - name: Static Type Checking
          run: |
            . .venv/bin/activate
            mypy src examples tests
        - name: Code Style Verification
          # Note: Ignore rules must be synchronized with pyproject.toml when modified
          run: |
            . .venv/bin/activate
            flake8 --ignore=E121,E123,E126,E226,E24,E704,E203,W503,W504,E501,F401,F403 src tests examples
        - name: Code Formatting Check
          run: |
            . .venv/bin/activate
            black --check src examples tests
        - name: Execute Test Suite
          run: |
            . .venv/bin/activate
            pytest --cov=src --cov-report=xml tests examples
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        - name: Submit Coverage Report
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
